// SPDX-License-Identifier: MIT
pragma solidity 0.8.24;

import {Test} from "forge-std/Test.sol";
import {HelperConfig} from "../../script/HelperConfig.s.sol";
import {AdoptToken} from "../../script/config/AdoptToken.s.sol";
import {RegistryWriter} from "../../src/utils/RegistryWriter.sol";
import {ProjectStore} from "../../src/utils/ProjectStore.sol";
import {ChainHandlers} from "../../script/utils/ChainHandlers.s.sol";
import {ProjectScratch} from "../utils/ProjectScratch.sol";

/// @dev External wrapper so `vm.expectRevert` observes the family-validation revert (an internal
/// library revert is inlined into the test frame otherwise).
contract StringWriteHarness {
    function writeString(string memory sel, string memory role, string memory name, string memory value) external {
        RegistryWriter.recordDeterministicString(sel, role, name, value);
    }
}

/// @title StringStoreNonEvmTest — area D (string store / non-EVM)
/// @notice The STRING-valued store surface for non-EVM (base58) artifacts: hex + base58
/// positive round-trips, every family-validation NEGATIVE as a NAMED revert (31-byte / 33-byte base58
/// decodes, invalid-alphabet `0 O I l`, hex-on-svm, base58-on-evm), the chainId-0 refusal that points
/// at the selectorName getter, two chainId-0 chains resolving to DISTINCT project files with NO
/// `project/0.json` ever created, the `local-<chainId>` anvil basename, the store-resolved SVM remote
/// feeding `applyChainUpdates`' exact encoding (no env), and the `adopt-token` non-EVM `runNonEvm` path.
/// Base58 test vectors were generated by an INDEPENDENT Python base58 (not the code under test).
contract StringStoreNonEvmTest is Test {
    // Real 32-byte Solana pubkeys (44-char base58, decode to exactly 32 bytes).
    string internal constant SVM_POOL = "ALh3xpZtujrfYZSiURBEHpeBFnzZEH37nY4BA4EHiiB5";
    string internal constant SVM_TOKEN = "BPympxtoS3GZmNcGiTxqsH6kyRgKiS9QFjfviSLaqxRE";
    // Negatives (independent Python base58): decode to 31 / 33 bytes respectively.
    string internal constant B58_DECODES_31 = "3cpvoZKJ28f1CDBboEmfEXMVVMcSQzBhTEMtecGWQ6v";
    string internal constant B58_DECODES_33 = "VnSuyHPLv3XWRZZCpFxQwumxzecjv5UK2pvXpv6DGvQA";
    // Invalid base58 alphabet (contains 'O', 'I', 'l', '0' — none in the base58 set), 44 chars.
    string internal constant B58_BAD_ALPHABET = "OIl0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
    string internal constant EVM_HEX = "0x1111111111111111111111111111111111111111";

    // UNIQUE per-test basenames (a shared basename races silently under forge's parallel test-case
    // execution: one test's setUp cleans the config while another is mid-write/read → parseJson EOF).
    string internal constant SEL_HEX = "zz-scratch-nonevm-hex";
    string internal constant SEL_SVM = "zz-scratch-nonevm-svm";
    string internal constant SEL_NEG31 = "zz-scratch-nonevm-neg31";
    string internal constant SEL_NEG33 = "zz-scratch-nonevm-neg33";
    string internal constant SEL_NEGALPHA = "zz-scratch-nonevm-negalpha";
    string internal constant SEL_NEGHEX = "zz-scratch-nonevm-neghex";
    string internal constant SEL_EVM_NEG = "zz-scratch-nonevm-evmneg";
    string internal constant SEL_SVM_A = "zz-scratch-nonevm-svma";
    string internal constant SEL_SVM_B = "zz-scratch-nonevm-svmb";
    string internal constant SEL_ADOPT = "zz-scratch-nonevm-adopt";
    string internal constant SEL_SVM_RES = "zz-scratch-nonevm-svmres";
    string internal constant SEL_LOCAL = "local-31337";

    uint64 internal constant SEL_A_SELECTOR = 8_893_100_000_000_000_001;
    uint64 internal constant SEL_B_SELECTOR = 8_893_100_000_000_000_002;
    uint64 internal constant SEL_SVM_SELECTOR = 8_893_100_000_000_000_003;
    uint64 internal constant SEL_ADOPT_SELECTOR = 8_893_100_000_000_000_004;
    uint64 internal constant SEL_NEG31_SELECTOR = 8_893_100_000_000_000_005;
    uint64 internal constant SEL_NEG33_SELECTOR = 8_893_100_000_000_000_006;
    uint64 internal constant SEL_NEGALPHA_SELECTOR = 8_893_100_000_000_000_007;
    uint64 internal constant SEL_NEGHEX_SELECTOR = 8_893_100_000_000_000_008;
    uint64 internal constant SEL_RES_SELECTOR = 8_893_100_000_000_000_009;

    StringWriteHarness internal harness;

    function setUp() public {
        harness = new StringWriteHarness();
        _clean();
    }

    /// @dev Sweeps this suite's scratch fixtures from setUp(): the revert-safe guarantee (a failed
    /// test leaves its fixtures for inspection until the next run). Each test additionally removes
    /// ONLY the fixtures it owns at the end of its body (suite siblings run in parallel), so a green
    /// run leaves no residue.
    function _clean() private {
        string[12] memory sels = [
            SEL_HEX,
            SEL_SVM,
            SEL_NEG31,
            SEL_NEG33,
            SEL_NEGALPHA,
            SEL_NEGHEX,
            SEL_EVM_NEG,
            SEL_SVM_A,
            SEL_SVM_B,
            SEL_ADOPT,
            SEL_SVM_RES,
            SEL_LOCAL
        ];
        for (uint256 i = 0; i < sels.length; i++) {
            ProjectScratch.clean(sels[i]);
        }
        // A stray project/0.json from a buggy prior run would poison the "no 0.json" assertion.
        string memory zero = string.concat(vm.projectRoot(), "/project/0.json");
        if (vm.exists(zero)) vm.removeFile(zero);
    }

    function _svmRevert(string memory value, string memory sel) internal pure returns (bytes memory) {
        return bytes(string.concat("[project] '", value, "' is not a valid SVM (base58, 32 bytes) address for ", sel));
    }

    // ---------------------------------------------------------------- positive round-trips

    // Hex (EVM): recordDeterministic round-trips through read/readDeployment (no config needed — EVM
    // family is the default when config/chains/<sel>.json is absent).
    function test_Hex_PositiveRoundTrip() public {
        address a = address(0x1234567890AbcdEF1234567890aBcdef12345678);
        RegistryWriter.recordDeterministic(SEL_HEX, "token", "T_Token", a);
        assertEq(RegistryWriter.read(SEL_HEX, "token"), a, "hex active.token round-trip");
        assertEq(RegistryWriter.readDeployment(SEL_HEX, "T_Token"), a, "hex deployment round-trip");
        ProjectScratch.clean(SEL_HEX);
    }

    // Base58 (SVM): recordDeterministicString round-trips through readString; the EVM getter read()
    // resolves address(0) for a non-EVM value (an EVM caller resolving a non-EVM chain).
    function test_Base58_PositiveRoundTrip() public {
        ProjectScratch.seedConfig(SEL_SVM, "svm", 0, SEL_SVM_SELECTOR);
        RegistryWriter.recordDeterministicString(SEL_SVM, "tokenPool", "P_pool", SVM_POOL);
        assertEq(RegistryWriter.readString(SEL_SVM, "tokenPool"), SVM_POOL, "base58 active.tokenPool round-trip");
        assertEq(RegistryWriter.read(SEL_SVM, "tokenPool"), address(0), "non-EVM value via EVM getter resolves 0");
        assertEq(
            RegistryWriter.readDeploymentString(SEL_SVM, "P_pool"), SVM_POOL, "base58 deployment string round-trip"
        );
        ProjectScratch.clean(SEL_SVM);
    }

    // ---------------------------------------------------------------- family-validation NEGATIVES

    function test_Neg_Base58Decodes31Bytes_NamedRevert() public {
        ProjectScratch.seedConfig(SEL_NEG31, "svm", 0, SEL_NEG31_SELECTOR);
        vm.expectRevert(_svmRevert(B58_DECODES_31, SEL_NEG31));
        harness.writeString(SEL_NEG31, "tokenPool", "P", B58_DECODES_31);
        ProjectScratch.clean(SEL_NEG31);
    }

    function test_Neg_Base58Decodes33Bytes_NamedRevert() public {
        ProjectScratch.seedConfig(SEL_NEG33, "svm", 0, SEL_NEG33_SELECTOR);
        vm.expectRevert(_svmRevert(B58_DECODES_33, SEL_NEG33));
        harness.writeString(SEL_NEG33, "tokenPool", "P", B58_DECODES_33);
        ProjectScratch.clean(SEL_NEG33);
    }

    function test_Neg_InvalidBase58Alphabet_NamedRevert() public {
        ProjectScratch.seedConfig(SEL_NEGALPHA, "svm", 0, SEL_NEGALPHA_SELECTOR);
        vm.expectRevert(_svmRevert(B58_BAD_ALPHABET, SEL_NEGALPHA));
        harness.writeString(SEL_NEGALPHA, "tokenPool", "P", B58_BAD_ALPHABET);
        ProjectScratch.clean(SEL_NEGALPHA);
    }

    // hex-on-svm: an EVM "0x…" address on an SVM chain fails base58 validation ('0' + 'x' are not the
    // base58 alphabet / wrong decode) with the NAMED SVM revert.
    function test_Neg_HexOnSvm_NamedRevert() public {
        ProjectScratch.seedConfig(SEL_NEGHEX, "svm", 0, SEL_NEGHEX_SELECTOR);
        vm.expectRevert(_svmRevert(EVM_HEX, SEL_NEGHEX));
        harness.writeString(SEL_NEGHEX, "tokenPool", "P", EVM_HEX);
        ProjectScratch.clean(SEL_NEGHEX);
    }

    // base58-on-evm: a base58 pubkey on an EVM chain fails EVM validation (no "0x" + 40 hex) with the
    // NAMED EVM revert. EVM family is the default (no config), which is the point.
    function test_Neg_Base58OnEvm_NamedRevert() public {
        vm.expectRevert(
            bytes(
                string.concat("[project] '", SVM_POOL, "' is not a valid EVM (0x + 40 hex) address for ", SEL_EVM_NEG)
            )
        );
        harness.writeString(SEL_EVM_NEG, "tokenPool", "P", SVM_POOL);
        ProjectScratch.clean(SEL_EVM_NEG);
    }

    // ---------------------------------------------------------------- chainId-0 refusal + distinct files

    // A chainId-keyed lookup for a chainId-0 (non-EVM) chain REFUSES and points at the selectorName getter.
    function test_ChainIdZero_GetSelectorName_Refuses() public {
        HelperConfig hc = new HelperConfig();
        vm.expectRevert(bytes("getSelectorName: non-EVM chains share chainId 0 - resolve by selectorName"));
        hc.getSelectorName(0);
    }

    // Two chainId-0 (non-EVM) chains resolve to DISTINCT project/<selectorName>.json files, and NO
    // project/0.json is ever created.
    function test_TwoChainIdZeroChains_DistinctFiles_NoZeroJson() public {
        ProjectScratch.seedConfig(SEL_SVM_A, "svm", 0, SEL_A_SELECTOR);
        ProjectScratch.seedConfig(SEL_SVM_B, "svm", 0, SEL_B_SELECTOR);
        RegistryWriter.recordDeterministicString(SEL_SVM_A, "tokenPool", "PA", SVM_POOL);
        RegistryWriter.recordDeterministicString(SEL_SVM_B, "tokenPool", "PB", SVM_TOKEN);

        assertTrue(vm.exists(ProjectStore.path(SEL_SVM_A)), "chain A project file exists");
        assertTrue(vm.exists(ProjectStore.path(SEL_SVM_B)), "chain B project file exists");
        assertEq(RegistryWriter.readString(SEL_SVM_A, "tokenPool"), SVM_POOL, "A resolves its own pool");
        assertEq(RegistryWriter.readString(SEL_SVM_B, "tokenPool"), SVM_TOKEN, "B resolves its own pool (no collision)");
        assertFalse(
            vm.exists(string.concat(vm.projectRoot(), "/project/0.json")), "project/0.json must NEVER be created"
        );
        ProjectScratch.clean(SEL_SVM_A);
        ProjectScratch.clean(SEL_SVM_B);
    }

    // The store is basename-agnostic: a `local-<chainId>` anvil selectorName is a valid, isolated store
    // key (gitignored via project/local-*.json), so local dev chains never collide.
    // Deliberate exception to the "tests write only zz-scratch-* project names" rule: the assertion IS
    // the exact `local-31337` basename, so the real name stays — guarded by the setUp() sweep plus the
    // scoped end-of-test clean below (no bundled chain is named `local-*`, so a leak can only shadow a
    // real anvil session's own scratch, never a public chain's project state).
    function test_LocalChainIdBasename_IsolatedStoreKey() public {
        address a = address(0xabCd567890aBcdef1234567890AbcDef12345678);
        RegistryWriter.recordDeterministic(SEL_LOCAL, "token", "L_Token", a);
        assertEq(ProjectStore.path(SEL_LOCAL), string.concat(vm.projectRoot(), "/project/local-31337.json"), "path");
        assertEq(RegistryWriter.read(SEL_LOCAL, "token"), a, "local-<chainId> basename round-trips");
        ProjectScratch.clean(SEL_LOCAL);
    }

    // ---------------------------------------------------------------- store-resolved feeds applyChainUpdates

    // A base58 SVM remote stored in project/<svm-chain>.json resolves through the selectorName-keyed
    // getter with ZERO env vars and encodes to the EXACT 32 bytes ApplyChainUpdates feeds into the
    // TokenPool.ChainUpdate (the `prepareChainAddressData(rawPoolAddress, SVM)` at ApplyChainUpdates.s.sol
    // line 577, with DEST_TOKEN_POOL unset so the store is the source). Independent Python decode as the
    // oracle. This replaces the env-only DEST_TOKEN_POOL path.
    function test_StoreResolvedSvmRemote_FeedsApplyChainUpdatesEncoding() public {
        // Precondition: no DEST_TOKEN_POOL override, so the store is the resolution source.
        if (bytes(vm.envOr("DEST_TOKEN_POOL", string(""))).length != 0) vm.skip(true);
        ProjectScratch.seedConfig(SEL_SVM_RES, "svm", 0, SEL_RES_SELECTOR);
        RegistryWriter.recordDeterministicString(SEL_SVM_RES, "tokenPool", "P_pool", SVM_POOL);

        // HelperConfig discovers the svm scratch chain and caches its base58 artifact (store, no env).
        HelperConfig hc = new HelperConfig();
        string memory resolved = hc.getDeployedTokenPoolString(SEL_SVM_RES);
        assertEq(resolved, SVM_POOL, "store-resolved base58 remote (no env)");

        // The exact ApplyChainUpdates encoding of the store-resolved remote is 32 raw bytes.
        bytes memory encoded = ChainHandlers.prepareChainAddressData(resolved, ChainHandlers.ChainFamily.SVM);
        assertEq(encoded.length, 32, "SVM remote encodes to exactly 32 bytes for applyChainUpdates");
        assertEq(keccak256(encoded), keccak256(_pythonDecodedSvmPool()), "encoded bytes != independent base58 decode");
        ProjectScratch.clean(SEL_SVM_RES);
    }

    /// @dev The independent (Python) base58 decode of SVM_POOL (ALh3xpZtujrfYZSiURBEHpeBFnzZEH37nY4BA4EHiiB5),
    /// as raw 32 bytes — the oracle for the encoder under test.
    function _pythonDecodedSvmPool() internal pure returns (bytes memory) {
        return hex"8ac480ec4e9718c0a011b0d5c542d42e8a4628f98d836f2f2acb4e9e2ac7e4d4";
    }

    // ---------------------------------------------------------------- adopt-token non-EVM path

    // `runNonEvm` (make adopt-token CHAIN=<svm> TOKEN_B58= POOL_B58=) declares base58 remotes into the
    // project store via the family-validated string writer — the non-EVM adopt path.
    function test_AdoptToken_RunNonEvm_Base58Path() public {
        ProjectScratch.seedConfig(SEL_ADOPT, "svm", 0, SEL_ADOPT_SELECTOR);
        new AdoptToken().runNonEvm(SEL_ADOPT, SVM_TOKEN, SVM_POOL);
        assertEq(RegistryWriter.readString(SEL_ADOPT, "token"), SVM_TOKEN, "runNonEvm declared the base58 token");
        assertEq(RegistryWriter.readString(SEL_ADOPT, "tokenPool"), SVM_POOL, "runNonEvm declared the base58 pool");
        ProjectScratch.clean(SEL_ADOPT);
    }

    // runNonEvm REFUSES an EVM chain (points at the address-typed run path).
    function test_AdoptToken_RunNonEvm_RefusesEvmChain() public {
        AdoptToken at = new AdoptToken();
        vm.expectRevert(
            bytes("ethereum-testnet-sepolia is an EVM chain - use the address-typed run(string,address,address) path")
        );
        at.runNonEvm("ethereum-testnet-sepolia", SVM_TOKEN, SVM_POOL);
    }
}
